name: Code Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        check: [dictionaries, tuples, slicing, strings, sets, recursion, lambda_functions, map, filter, reduce, exceptions, file_operations, regex]

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run code analysis for ${{ matrix.check }}
      run: python .github/workflows/code_analysis.py ${{ matrix.check }}
