name: Hitos

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sprint: [sprint_1, sprint_2, sprint_3, sprint_4, sprint_5, parcial_1, parcial_2, final]
    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run code analysis for ${{ matrix.sprint }}
      run: |
        case ${{ matrix.sprint }} in
          sprint_1)
            checks=(lists dictionaries tuples slicing strings sets)
            ;;
          sprint_2)
            checks=(lambda_functions map filter reduce file_operations)
            ;;
          sprint_3)
            checks=(regex)
            ;;
          sprint_4)
            checks=(exceptions)
            ;;
          sprint_5)
            checks=(recursion unit_tests)
            ;;
          parcial_1)
            checks=(lists dictionaries tuples slicing strings sets)
            ;;
          parcial_2)
            checks=(lists dictionaries tuples slicing strings sets lambda_functions map filter reduce file_operations regex exceptions)
            ;;
          final)
            checks=(lists dictionaries tuples slicing strings sets lambda_functions map filter reduce file_operations regex exceptions recursion unit_tests)
            ;;
        esac
        for check in "${checks[@]}"; do
          python .github/workflows/code_analysis.py "$check"
        done
