name: Code Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        check:
          sprint_1: [lists, dictionaries, tuples, slicing, strings, sets]
          sprint_2: [lambda_functions, map, filter, reduce, file_operations]
          sprint_3: [regex]
          sprint_4: [exceptions]
          sprint_5: [recursion, unit_tests]
          parcial_1: [lists, dictionaries, tuples, slicing, strings, sets]
          parcial_2: [lists, dictionaries, tuples, slicing, strings, sets, lambda_functions, map, filter, reduce, file_operations, regex, exceptions]
          final: [lists, dictionaries, tuples, slicing, strings, sets, lambda_functions, map, filter, reduce, file_operations, regex, exceptions, recursion, unit_tests]


    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run code analysis for ${{ matrix.sprint }} - ${{ matrix.check }}
      run: |
        for check in ${{ matrix.sprint }}; do
          python .github/workflows/code_analysis.py "$check"
        done